language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - SYMFONY_VERSION=4.4.* # LTS (until 11/2023)
    - SYMFONY_VERSION=5.0.* # (until 07/2020)
    - SYMFONY_VERSION=5.1.* # (until 01/2021)

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
    - composer update

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-text

after_success:
    - travis_retry php vendor/bin/php-coveralls

matrix:
    exclude:
        - php: 7.1
          env: SYMFONY_VERSION=5.0.* # requires PHP ^7.2.5
        - php: 7.1
          env: SYMFONY_VERSION=5.1.* # requires PHP ^7.2.5
    allow_failures:
        - php: nightly
        - env: SYMFONY_VERSION=dev-master

notifications:
    email:
        - "gregurco.vlad@gmail.com"
